# Generated by Django 4.2.3 on 2023-07-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_created_at_alter_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
